services:
  frontend:
    image: alykhan02/quirknotes_frontend:latest
    ports:
    - "3000:3000"
  backend:
    image: alykhan02/quirknotes_backend:latest
    build:
      context: .
      dockerfile: dockerfile_backend
      target: backend
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
