# Use the official Node.js image as the base image for backend
FROM node:20.0.0-alpine AS backend

# Set the working directory for backend
WORKDIR /app/quirknotes/backend

# Copy backend package files to the working directory
COPY quirknotes/backend/package*.json ./

# Install the backend dependencies
RUN npm install

# Copy the backend source code to the working directory
COPY quirknotes/backend/ ./

# Start the backend server
CMD ["npm", "run", "dev"]